flask/PupAdoption/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class OwnerForm(FlaskForm):
    owner = StringField('Owner Name: ')
    id = IntegerField("ID number of the Puppy: ")
    submit = SubmitField('Add Owner')

flask/PupAdoption/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of the Puppy: ')
    toys = StringField("Puppy's Toy items: ")
    submit = SubmitField('Add Puppy')

class DelForm(FlaskForm):
    id = IntegerField("ID number of the Puppy to be removed: ")
    submit = SubmitField('Delete Puppy')

flask/PupAdoption/toys/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class ToyForm(FlaskForm):
    toys = StringField("Puppy's Toy item/s: ")
    id = IntegerField("ID number of the Puppy: ")
    submit = SubmitField('Add Toy/s')

flask/PupAdoption/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email, EqualTo
from PupAdoption.pup_models import User
from PupAdoption import db

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    passwd = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    passwd = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register!')

    def check_email(self, efield):
        if db.session.execute(db.select(User).filter_by(email=efield)):
            raise ValidationError('This Email is already registered!!')
        return
        
    def check_username(self, ufield):
        if db.session.execute(db.select(User).filter_by(username=ufield)): 
            raise ValidationError('This username is already taken!')
        return
        

flask/PupAdoption/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from flask_login import LoginManager
import os

class Base(DeclarativeBase):
    pass

db = SQLAlchemy(model_class=Base)

basedir = os.path.abspath(os.path.dirname(__file__))
db_file = str('sqlite:///' + basedir + '/pup_data.sqlite')

app = Flask(__name__)
app.config['SECRET_KEY'] = "mysecretkey"
app.config["SQLALCHEMY_DATABASE_URI"] = db_file
db.init_app(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

from PupAdoption.puppies.views import puppies_blueprints
from PupAdoption.owners.views import owners_blueprints
from PupAdoption.toys.views import toys_blueprints
from PupAdoption.users.views import users_blueprints

app.register_blueprint(puppies_blueprints, url_prefix='/puppies')
app.register_blueprint(owners_blueprints, url_prefix='/owners')
app.register_blueprint(toys_blueprints, url_prefix='/toys')
app.register_blueprint(users_blueprints, url_prefix='/users')

with app.app_context():
    db.create_all()

#Base.metadata.create_all(engine)

flask/PupAdoption/owners/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from PupAdoption import db
from PupAdoption.pup_models import Owner
from PupAdoption.owners.forms import OwnerForm

owners_blueprints = Blueprint('owners', __name__, template_folder='templates/owners')

@owners_blueprints.route('/add', methods=['GET', 'POST'])
@login_required
def add_owner():
    oform = OwnerForm()
    if oform.validate_on_submit():
        owner = oform.owner.data
        id = oform.id.data
        pup_owner = Owner(owner, id)
        db.session.add(pup_owner)
        db.session.commit()
        pup_name = pup_owner.puppy.name
        flash("Owner '%s' for Puppy %s - Successfully added!" % (pup_owner.name, pup_name))
        return redirect(url_for('owners.add_owner'))
    return render_template('add_owner.html', form = oform)

flask/PupAdoption/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from PupAdoption import db
from PupAdoption.pup_models import Puppy
from PupAdoption.puppies.forms import AddForm, DelForm

puppies_blueprints = Blueprint('puppies', __name__, template_folder='templates/puppies')

@puppies_blueprints.route('/add', methods=['GET', 'POST'])
@login_required
def add_pup():
    aform = AddForm()
    if aform.validate_on_submit():
        name = aform.name.data
        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()
        flash("Puppy %s - Successfully added!" % name)
        return redirect(url_for('puppies.add_pup'))
    return render_template('add.html', form = aform)

@puppies_blueprints.route('/list')
@login_required
def list_pup():  
    puppies = db.session.execute(db.select(Puppy).order_by(Puppy.id)).scalars()
    return render_template('list.html', puppies=puppies)
    
@puppies_blueprints.route('/delete', methods=['GET', 'POST'])
@login_required
def del_pup():
    dform = DelForm()
    if dform.validate_on_submit():
        id = dform.id.data
        rm_pup = db.one_or_404(db.select(Puppy).filter_by(id=id))
        rm_pup_name = rm_pup.name
        rm_owner = rm_pup.owner
        rm_toys = rm_pup.toys
        print(rm_pup, "\n", rm_owner, "\n", rm_toys)
        db.session.delete(rm_pup)
        if rm_owner:
            db.session.delete(rm_owner)
        if rm_toys:
            for rm_toy in rm_toys:
                db.session.delete(rm_toy)
        db.session.commit()
        flash("Puppy '%s' with ID %s - Successfully deleted!!" % (rm_pup_name, id))
        return redirect(url_for('puppies.del_pup'))
    return render_template('del.html', form = dform)

flask/PupAdoption/toys/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from PupAdoption import db
from PupAdoption.pup_models import Toy, Puppy
from PupAdoption.toys.forms import ToyForm

toys_blueprints = Blueprint('toys', __name__, template_folder='templates/toys')

@toys_blueprints.route('/add', methods=['GET', 'POST'])
@login_required
def add_toys():
    tform = ToyForm()
    if tform.validate_on_submit():
        toys = tform.toys.data
        id = tform.id.data
        pup_toys = Toy(toys, id)
        db.session.add(pup_toys)
        db.session.commit()
        pup_name = pup_toys.puppy.name
        puppy = Puppy(pup_name)
        flash("Toys '%s' for Puppy %s - Successfully added!" % (toys, pup_name))
        return redirect(url_for('toys.add_toys'))
    return render_template('add_toys.html', form = tform)

flask/PupAdoption/users/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import login_user, login_required, logout_user
from PupAdoption.pup_models import User
from PupAdoption import db
from PupAdoption.users.forms import LoginForm, RegistrationForm

users_blueprints = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprints.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome.html')

@users_blueprints.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out!!")
    return redirect(url_for('home'))

@users_blueprints.route('/login', methods=['GET', 'POST'])
def login():
    lform = LoginForm()
    if lform.validate_on_submit():
        user = db.session.execute(db.select(User).filter_by(email=lform.email.data)).scalar()
        if user.check_password(lform.passwd.data) and user is not None:
            login_user(user)
            flash('%s - Logged in Successfully!' % user.username)
            nextpg = request.args.get('next')
            if nextpg == None or not nextpg[0] == '/':
                nextpg = url_for('users.welcome_user')
            return redirect(nextpg)
    return render_template('login.html', form=lform)

@users_blueprints.route('/register', methods=['GET', 'POST'])
def register():
    rform = RegistrationForm()
    if rform.validate_on_submit():
        user = User(email=rform.email.data, 
                    username=rform.username.data, 
                    passwd=rform.passwd.data)
        rform.check_email(user.email)
        rform.check_username(user.username)
        db.session.add(user)
        db.session.commit()
        flash("User %s - Registered Successfully!!" % user.username)
        return redirect(url_for('users.login'))
    return render_template('register.html', form=rform)

flask/PupAdoption/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Puppy Adoption</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse navbar-nav" id="navbarNav">
                <h4><a class="nav-item nav-link active" href="{{ url_for('home')}}">Home</a></h4>
                {% if current_user.is_authenticated  %}
                <h4><a class="nav-item nav-link" href="{{url_for('puppies.add_pup')}}">Add</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('puppies.list_pup')}}">List</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('puppies.del_pup')}}">Delete</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('owners.add_owner')}}">Owner</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('toys.add_toys')}}">Toys</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a></h4>
                {% else %}
                <h4><a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a></h4>
                <h4><a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a></h4>
                {% endif %}
            </div>
        </nav>
 
        {% block snippet %}

        {% endblock %}

    </body>
</html>

flask/PupAdoption/templates/home.html
{% extends 'base.html' %}

{% block snippet %}
<div class="jumbotron">
  <h2>Welcome to Puppy Adoption Site!</h2>
</div>
{% endblock %}

flask/templates/ff_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    {% for mesg in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
        {{ mesg }}
    </div>
    {% endfor %}
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.breed.label }} {{ form.breed() }}
        {{ form.submit() }}
    </form>
</body>

flask/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    {% for mesg in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
        {{ mesg }}
    </div>
    {% endfor %}
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.breed.label }} {{ form.breed() }}
        {{ form.submit() }}
    </form>
</body>

flask/templates/pup_add.html
{% extends "pup_base.html" %}
{% block snippet %}
<div class="jumbotron">
    <h1>Do you have a Puppy for adoption?</h1>
    <p>Add a new Puppy to our DB!</p>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.name.label }} {{ form.name() }}
        {{ form.owner.label }} {{ form.owner() }}
        {{ form.toys.label }} {{ form.toys() }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/templates/pup_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Puppy Adoption</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse navbar-nav" id="navbarNav">
                <a class="nav-item nav-link active" href="{{ url_for('index')}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('add_pup')}}">Add</a>
                <a class="nav-item nav-link" href="{{url_for('list_pup')}}">List</a>
                <a class="nav-item nav-link" href="{{url_for('del_pup')}}">Delete</a>
                <a class="nav-item nav-link" href="{{url_for('owner_pup')}}">Owner</a>
                <a class="nav-item nav-link" href="{{url_for('toys_pup')}}">Toys</a>
            </div>
        </nav>

        {% block snippet %}

        {% endblock %}

    </body>
</html>

flask/templates/pup_del.html
{% extends "pup_base.html" %}
{% block snippet %}
{% for Msg in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{Msg}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
{% endfor %}
    <div class="jumbotron">
        <h2>Did a Puppy get adopted?</h2>
        <p>If yes, please remove the Puppy from our DB.</p>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.id.label }} {{ form.id() }}
            {{ form.submit() }}
        </form>
    </div>
{% endblock %}

flask/templates/pup_home.html
{% extends 'pup_base.html' %}

{% block snippet %}
<div class="jumbotron">
  <h2>Welcome to Puppy Adoption Site!</h2>
</div>
{% endblock %}

flask/templates/pup_list.html
{% extends "pup_base.html" %}
{% block snippet %}
    <div class="jumbotron">
        <h1>List of all Puppies at this Org.</h1>
            <ul>
                {% for pup in puppies %}
                    <li><h4>{{ pup }}</h4></li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

flask/templates/pup_owner.html
{% extends "pup_base.html" %}
{% block snippet %}
{% for Msg in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{Msg}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
{% endfor %}
<div class="jumbotron">
    <h1>Add Owner for a Puppy.</h1>
    <p>Add Puppy Owner to our DB!</p>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.owner.label }} {{ form.owner() }}
        {{ form.id.label }} {{ form.id() }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/templates/pup_toys.html
{% extends "pup_base.html" %}
{% block snippet %}
{% for Msg in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{Msg}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
{% endfor %}
<div class="jumbotron">
    <h1>Add Toy/s for a Puppy.</h1>
    <p>Add Puppy Toy/s to our DB!</p>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.toys.label }} {{ form.toys() }}
        {{ form.id.label }} {{ form.id() }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/templates/signup.html
{% extends "base.html" %}
{% block snippet %}
<div class="container-fluid">
    <h2>Welcome to Sign Up Page!</h2>
    <p>Please fill out this form -</p>
    <form action={{ url_for('thank_you') }}>
        <label for="first">First Name:</label>
        <input type="text" name="first">
        <label for="last">Last Name:</label>
        <input type="text" name="last">
        <br><br>
        <label for="username">Username:</label>
        <input type="text" name="username">
        <br><br>
        <input class="btn btn-primary" type="submit" value="Submit Form">
    </form>
</div>
{% endblock %}

flask/templates/testform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testform</title>
</head>
<body>
    <h1>Testform HTML</h1>
</body>
</html>

flask/templates/testhtml.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Assessment Test HTML</title>
        <link rel="stylesheet" href="/Users/abhat/GIT/Python/templates/mycss/testcss.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    </head>

    <body>
        <h1>Puppy Adoption Page</h1>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        <h3>Please enter information to adopt a Puppy</h3>
        <p>Please fill in: First Name, Last Name, Password and Email fields are required</p>
        <form method="get">
            <label for="firstname">First Name: </label>
            <input type="text" id="firstname" name="first_name" placeholder="First Name">
            <label for="lastname">Last Name: </label>
            <input type="text" id="lastname" name="last_name" placeholder="Last Name">
            <br> <br>
            <label for="email">Email: </label>
            <input type="email" id="email" name="email_id" placeholder="example@abc.com">
            <label for="pass">Password: </label>
            <input type="password" id="pass" name="passwd" placeholder="">
            <br> <br>
            <span>Are you over the age of 18?</span>
            <br>
            <label for="yesguy">Yes: </label>
            <input type="radio" id="yesguy" name="age_choice" value="yes">
            <label for="noguy">No: </label>
            <input type="radio" id="noguy" name="age_choice" value="no">
            <br>
            <span>Do you have a Credit Card or PayPal?</span>
            <br>
            <select name="pay_method">
                <option value="CreditCard">Credit Card</option>
                <option value="PayPal">PayPal</option>
            </select>
            <br><br>
            <input type="submit" value="Submit Feedback">
        </form>
        <br>

        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="/Users/abhat/Downloads/cutepuppies1.jpg" class="d-block-w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="/Users/abhat/Downloads/cutepuppies2.jpg" class="d-block-w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="/Users/abhat/Downloads/cutepuppies3.jpg" class="d-block-w-100" alt="">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </body>
</html>

flask/templates/thankyou.html
{% extends 'base.html' %}
{% block snippet %}
<div class="container-fluid">
    {% if failures != [] %}
    <ul>
        {% for words in failures %}
        <li><h2>{{ words }}</h2></li>
        {% endfor %}
    </ul>
    {% else %}
    <ul>
        <li><h2>Username "{{ uname }}" passed all verification requirements.</h2></li>
        <li><h2>"{{ first }} {{ last }}" has been registered. Thank you!</h2></li>
    </ul>
    {% endif %}
</div>
{% endblock %}